apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: todo-app-backend-config
spec:
  # Temporarily disabled to debug 403 errors
  # securityPolicy:
  #   name: todo-app-security-policy
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthz
