resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - backend-config.yaml
  - create-iam-user-job.yaml
  - db-init-job.yaml
  - verify-job.yaml
  - load-generator.yaml
  - pod-monitoring.yaml
  - policies/template-required-labels.yaml
  - policies/constraint-ns-owner.yaml
  - rollouts/analysis-smoke-test.yaml
  - rollouts/todo-app-rollout.yaml
