resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - managed-certificate.yaml
  - backend-config.yaml
  - create-iam-user-job.yaml
  - db-init-job.yaml
  - verify-job.yaml
  - load-generator.yaml
  - pod-monitoring.yaml
  - policies/template-required-labels.yaml
  - policies/constraint-ns-owner.yaml
  - rollouts/analysis-smoke-test.yaml
  - rollouts/todo-app-rollout.yaml
  - pdb.yaml
  - policies/template-disallow-latest.yaml
  - policies/constraint-no-latest-tag.yaml
  - policies/template-required-resource-limits.yaml
  - policies/constraint-resource-limits.yaml

images:
  - name: todo-app-go
    newName: us-central1-docker.pkg.dev/smcghee-todo-p15n-38a6/todo-app-go/todo-app-go
    digest: sha256:12e095a73c8e48e49232cb10447e56a9e8a35fd8a0b89f8709fec2ced9040f5b
