apiVersion: v1
kind: Service
metadata:
  name: todo-app-go-service
  namespace: todo-app
  labels:
    app: todo-app-go
  annotations:
    cloud.google.com/backend-config: '{"default": "todo-app-backend-config"}'
spec:
  selector:
    app: todo-app-go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
