apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: argocd-monitoring
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  endpoints:
  - port: 8083 # ArgoCD Server metrics port
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: argocd-repo-server-monitoring
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  endpoints:
  - port: 8084 # Repo Server metrics port
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: argocd-application-controller-monitoring
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  endpoints:
  - port: 8082 # Application Controller metrics port
    path: /metrics
    interval: 30s
